### ISSUE TITLE
Remove Telegram token

### ISSUE THREAD

**Issue by egueli** [Constantini21/Prenotami-Passport#1]
Please remove the Telegram token at `src/services/telegram.ts`, or anyone that tries your program may send you unwanted messages.

**Comment by egueli** [comment]
Also the Telegram user ID at `src/services/telegramUsers.ts`.

By the way, good work! I'm testing it right now to try obtaining an appointment for my Italian national ID.

**Comment by Constantini21** [comment]
ok ;)
